data_path: ./data/MG.hepdecay/
save_dir: ./tmp/saver
source_domains:
    - ttbar 
    - 2hdm425-325
    - zprime1000
source_phase:
    - 500000
    - 50000
    - 50000
var_names:
    - features
    - label_graphs
    - label_edges
zarr_args_a: &zarr_args_a
    chunk: 10000
    output_dir: ./db/hepdecay.zarr
    mode: a
zarr_args_w: &zarr_args_w
    chunk: 10000
    output_dir: ./db/hepdecay.zarr
    mode: w
sg_args_a:
    backend: hybrid
    backend_args: *zarr_args_a
    data_id: hepdecay
sg_args_w:
    backend: hybrid
    backend_args: *zarr_args_w
    data_id: hepdecay
task_args:
    num_epochs: 100
    num_workers: 4
    device: 'cuda'
    batch_size: 256
    batch_sampler: True
    optimizer: SGD
    optimizer_args:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.00005
    metrics:
        - loss
        - subloss
    scheduler: CosineAnnealingLR
    scheduler_args:
        T_max: 100
        eta_min: 0.0001
    max_patience: 100
    loss: CrossEntropyLoss
    input_var_names: features
    output_var_names:
        - pred_edges
        - pred_graphs
        - attn_edges
        - attn_graphs
    pred_var_names:
        - pred_edges
        - pred_graphs
    true_var_names:
        - label_edges
        - label_graphs
    torchinfo: False
    verbose: 1
agent_args:
    dump_all_results: True
    metric: AUCMetric
    metric_args:
        var_names: 'pred_graphs label_graphs'
